import {
  Client,
  Contract,
  ReceivableItem,
  PayableItem,
  ActionItem,
  PipelineDeal,
  Integration,
  TimelineEvent,
  ServiceInvoice,
  AsaasChargeItem,
  BankAccount,
  BankTransaction,
} from './types';

export const initialClients: Client[] = [
  {
    id: 'cli-aurora',
    name: 'Aurora Marketing Digital',
    tradeName: 'Aurora Marketing',
    document: '34.892.120/0001-44',
    contactName: 'Camila Guimarães',
    contactEmail: 'camila@auroramarketing.com.br',
    contactPhone: '(11) 98452-1920',
    responsible: 'Marlon Ribeiro',
    services: ['Gestão de Tráfego', 'Inbound Marketing'],
    activeContractsCount: 1,
    monthlyRevenue: 7200,
    financialStatus: 'inadimplente',
    healthScore: 'atencao',
    lastActivity: 'Há 3 horas',
    city: 'São Paulo',
    state: 'SP',
    segment: 'Marketing & Mídia',
    createdAt: '12/03/2025',
    openBalance: 2450,
    avatarColor: 'bg-amber-500',
  },
  {
    id: 'cli-horizonte',
    name: 'Studio Horizonte Arquitetura Ltda',
    tradeName: 'Studio Horizonte',
    document: '28.192.403/0001-92',
    contactName: 'Lucas Ferraz',
    contactEmail: 'lucas@studiohorizonte.arq.br',
    contactPhone: '(21) 97120-4389',
    responsible: 'Marlon Ribeiro',
    services: ['Assessoria de Comunicação', 'Branding'],
    activeContractsCount: 2,
    monthlyRevenue: 11400,
    financialStatus: 'em_dia',
    healthScore: 'saudavel',
    lastActivity: 'Ontem às 16:40',
    city: 'Rio de Janeiro',
    state: 'RJ',
    segment: 'Arquitetura & Design',
    createdAt: '08/01/2025',
    openBalance: 0,
    avatarColor: 'bg-emerald-500',
  },
  {
    id: 'cli-vitta',
    name: 'Clínica Integrada Vitta Medicina',
    tradeName: 'Clínica Vitta',
    document: '19.782.934/0001-18',
    contactName: 'Dra. Beatriz Menezes',
    contactEmail: 'beatriz@clinicavitta.com.br',
    contactPhone: '(31) 99312-8874',
    responsible: 'Helena Duarte',
    services: ['Gestão de Tráfego', 'Mídias Sociais'],
    activeContractsCount: 1,
    monthlyRevenue: 3800,
    financialStatus: 'em_dia',
    healthScore: 'saudavel',
    lastActivity: 'Há 2 dias',
    city: 'Belo Horizonte',
    state: 'MG',
    segment: 'Saúde & Bem-estar',
    createdAt: '19/05/2025',
    openBalance: 0,
    avatarColor: 'bg-indigo-500',
  },
  {
    id: 'cli-alpha',
    name: 'Alpha Tecnologia e Sistemas',
    tradeName: 'Alpha Tecnologia',
    document: '42.610.778/0001-31',
    contactName: 'Rodrigo Siqueira',
    contactEmail: 'rodrigo@alphatec.io',
    contactPhone: '(11) 96522-3104',
    responsible: 'Marlon Ribeiro',
    services: ['Consultoria de Crescimento', 'SEO Técnico'],
    activeContractsCount: 1,
    monthlyRevenue: 8500,
    financialStatus: 'em_dia',
    healthScore: 'saudavel',
    lastActivity: 'Hoje às 10:15',
    city: 'Campinas',
    state: 'SP',
    segment: 'Tecnologia & SaaS',
    createdAt: '14/08/2024',
    openBalance: 0,
    avatarColor: 'bg-blue-600',
  },
  {
    id: 'cli-costa',
    name: 'Costa & Associados Consultoria',
    tradeName: 'Costa Consultoria',
    document: '14.520.108/0001-65',
    contactName: 'Eduardo Costa',
    contactEmail: 'eduardo@costaconsultoria.com.br',
    contactPhone: '(41) 98845-9012',
    responsible: 'Helena Duarte',
    services: ['Estratégia Digital'],
    activeContractsCount: 1,
    monthlyRevenue: 4500,
    financialStatus: 'pendente',
    healthScore: 'atencao',
    lastActivity: 'Há 5 dias',
    city: 'Curitiba',
    state: 'PR',
    segment: 'Consultoria Empresarial',
    createdAt: '03/09/2025',
    openBalance: 4500,
    avatarColor: 'bg-violet-600',
  },
  {
    id: 'cli-exclusive',
    name: 'Exclusive Motors Concessionária',
    tradeName: 'Exclusive Motors',
    document: '07.319.482/0001-09',
    contactName: 'Renato Valente',
    contactEmail: 'renato@exclusivemotors.com.br',
    contactPhone: '(11) 97782-4411',
    responsible: 'Marlon Ribeiro',
    services: ['Performance & Leads'],
    activeContractsCount: 1,
    monthlyRevenue: 5900,
    financialStatus: 'inadimplente',
    healthScore: 'critico',
    lastActivity: 'Há 4 dias',
    city: 'São Paulo',
    state: 'SP',
    segment: 'Automotivo',
    createdAt: '10/02/2025',
    openBalance: 2450,
    avatarColor: 'bg-rose-600',
  },
];

export const initialContracts: Contract[] = [
  {
    id: 'ctr-1',
    code: 'CON-2026-0042',
    clientId: 'cli-aurora',
    clientName: 'Aurora Marketing',
    title: 'Contrato de Performance Digital & Inbound',
    service: 'Gestão de Tráfego',
    value: 7200,
    billingCycle: 'mensal',
    startDate: '01/01/2026',
    endDate: '31/12/2026',
    dueDay: 10,
    status: 'ativo',
    progressStep: 5,
    asaasStatus: 'sincronizado',
    responsible: 'Marlon Ribeiro',
    reajusteIndex: 'IPCA anual',
    lastInvoiceSent: '10/08/2026',
  },
  {
    id: 'ctr-2',
    code: 'CON-2026-0038',
    clientId: 'cli-horizonte',
    clientName: 'Studio Horizonte',
    title: 'Assessoria de Comunicação & Branding Mensal',
    service: 'Assessoria de Comunicação',
    value: 11400,
    billingCycle: 'mensal',
    startDate: '15/02/2026',
    endDate: '14/02/2027',
    dueDay: 15,
    status: 'ativo',
    progressStep: 5,
    asaasStatus: 'sincronizado',
    responsible: 'Marlon Ribeiro',
    reajusteIndex: 'IGP-M anual',
    lastInvoiceSent: '15/08/2026',
  },
  {
    id: 'ctr-3',
    code: 'CON-2026-0049',
    clientId: 'cli-vitta',
    clientName: 'Clínica Vitta',
    title: 'Posicionamento Digital para Médicos e Especialistas',
    service: 'Mídias Sociais',
    value: 3800,
    billingCycle: 'mensal',
    startDate: '01/06/2026',
    endDate: '31/05/2027',
    dueDay: 5,
    status: 'ativo',
    progressStep: 5,
    asaasStatus: 'sincronizado',
    responsible: 'Helena Duarte',
    reajusteIndex: 'IPCA anual',
    lastInvoiceSent: '05/09/2026',
  },
  {
    id: 'ctr-4',
    code: 'CON-2026-0055',
    clientId: 'cli-alpha',
    clientName: 'Alpha Tecnologia',
    title: 'Consultoria de Growth e Otimização Orgânica',
    service: 'Consultoria de Crescimento',
    value: 8500,
    billingCycle: 'mensal',
    startDate: '01/08/2026',
    endDate: '31/07/2027',
    dueDay: 20,
    status: 'ativo',
    progressStep: 5,
    asaasStatus: 'sincronizado',
    responsible: 'Marlon Ribeiro',
    reajusteIndex: 'IPCA anual',
  },
  {
    id: 'ctr-5',
    code: 'CON-2026-0058',
    clientId: 'cli-costa',
    clientName: 'Costa Consultoria',
    title: 'Renovação e Expansão de Estratégia Digital',
    service: 'Estratégia Digital',
    value: 4500,
    billingCycle: 'mensal',
    startDate: '10/09/2026',
    endDate: '09/09/2027',
    dueDay: 10,
    status: 'aguardando_assinatura',
    progressStep: 2,
    asaasStatus: 'pendente',
    responsible: 'Helena Duarte',
    reajusteIndex: 'IPCA anual',
  },
  {
    id: 'ctr-6',
    code: 'CON-2025-0019',
    clientId: 'cli-exclusive',
    clientName: 'Exclusive Motors',
    title: 'Geração Contínua de Leads Qualificados',
    service: 'Performance & Leads',
    value: 5900,
    billingCycle: 'mensal',
    startDate: '01/10/2025',
    endDate: '30/09/2026',
    dueDay: 5,
    status: 'a_renovar',
    progressStep: 5,
    asaasStatus: 'sincronizado',
    responsible: 'Marlon Ribeiro',
    reajusteIndex: 'IPCA anual',
  },
];

export const initialReceivables: ReceivableItem[] = [
  {
    id: 'rec-1',
    clientId: 'cli-aurora',
    clientName: 'Aurora Marketing',
    contractCode: 'CON-2026-0042',
    description: 'Mensalidade de Gestão de Tráfego - Competência 08/2026',
    dueDate: '02/09/2026',
    amount: 2450,
    method: 'pix',
    status: 'vencida',
    invoiceStatus: 'pendente',
    sentNotification: true,
    provider: 'asaas',
  },
  {
    id: 'rec-2',
    clientId: 'cli-exclusive',
    clientName: 'Exclusive Motors',
    contractCode: 'CON-2025-0019',
    description: 'Campanhas de Performance - Parcela 11/12',
    dueDate: '03/09/2026',
    amount: 2450,
    method: 'boleto',
    status: 'vencida',
    invoiceStatus: 'pendente',
    sentNotification: true,
    provider: 'asaas',
  },
  {
    id: 'rec-3',
    clientId: 'cli-vitta',
    clientName: 'Clínica Vitta',
    contractCode: 'CON-2026-0049',
    description: 'Mensalidade Posicionamento Digital - Setembro/2026',
    dueDate: '05/09/2026',
    amount: 3800,
    method: 'pix',
    status: 'recebida',
    invoiceStatus: 'emitida',
    sentNotification: true,
    provider: 'asaas',
    paidAt: '05/09/2026 às 09:12',
  },
  {
    id: 'rec-4',
    clientId: 'cli-costa',
    clientName: 'Costa Consultoria',
    contractCode: 'CON-2026-0058',
    description: 'Primeira Parcela do Novo Contrato Estratégico',
    dueDate: '10/09/2026',
    amount: 4500,
    method: 'boleto',
    status: 'pendente',
    invoiceStatus: 'pendente',
    sentNotification: false,
    provider: 'asaas',
  },
  {
    id: 'rec-5',
    clientId: 'cli-horizonte',
    clientName: 'Studio Horizonte',
    contractCode: 'CON-2026-0038',
    description: 'Assessoria de Comunicação e Branding - Parcela 07/12',
    dueDate: '15/09/2026',
    amount: 11400,
    method: 'pix',
    status: 'agendada',
    invoiceStatus: 'pendente',
    sentNotification: false,
    provider: 'asaas',
  },
  {
    id: 'rec-6',
    clientId: 'cli-alpha',
    clientName: 'Alpha Tecnologia',
    contractCode: 'CON-2026-0055',
    description: 'Consultoria de Growth - Competência 09/2026',
    dueDate: '20/09/2026',
    amount: 8500,
    method: 'cartao',
    status: 'agendada',
    invoiceStatus: 'pendente',
    sentNotification: false,
    provider: 'asaas',
  },
];

export const initialPayables: PayableItem[] = [
  {
    id: 'pay-1',
    supplier: 'Google Ads & Meta Ads Corporate',
    description: 'Verba de Mídia Gerenciada - Faturamento Direto',
    category: 'Custos Operacionais',
    costCenter: 'Operação de Tráfego',
    dueDate: '08/09/2026',
    amount: 32400,
    status: 'agendado',
    responsible: 'Marlon Ribeiro',
    recurrence: 'mensal',
    hasReceipt: true,
  },
  {
    id: 'pay-2',
    supplier: 'Amazon Web Services (AWS)',
    description: 'Infraestrutura Cloud e Servidores dos Clientes',
    category: 'Serviços de Terceiros / Software',
    costCenter: 'Tecnologia',
    dueDate: '12/09/2026',
    amount: 4120,
    status: 'pendente',
    responsible: 'Marlon Ribeiro',
    recurrence: 'mensal',
    hasReceipt: true,
  },
  {
    id: 'pay-3',
    supplier: 'HubSpot Brasil Ltda',
    description: 'Licenciamento CRM e Marketing Automation',
    category: 'Softwares & Ferramentas',
    costCenter: 'Comercial & Operação',
    dueDate: '15/09/2026',
    amount: 5850,
    status: 'agendado',
    responsible: 'Marlon Ribeiro',
    recurrence: 'mensal',
    hasReceipt: true,
  },
  {
    id: 'pay-4',
    supplier: 'Espaço WeWork Paulista',
    description: 'Locação de Escritório e Salas de Reunião',
    category: 'Infraestrutura & Instalações',
    costCenter: 'Administrativo',
    dueDate: '20/09/2026',
    amount: 8900,
    status: 'agendado',
    responsible: 'Helena Duarte',
    recurrence: 'mensal',
    hasReceipt: true,
  },
];

export const initialActionItems: ActionItem[] = [
  {
    id: 'act-1',
    priority: 'urgente',
    category: 'financeiro',
    title: 'Cobrança vencida há 3 dias (R$ 2.450)',
    description: 'Aurora Marketing não realizou a liquidação via Pix da mensalidade referente ao mês de agosto.',
    value: 2450,
    dueDate: '02/09/2026',
    clientId: 'cli-aurora',
    clientName: 'Aurora Marketing',
    responsible: 'Marlon Ribeiro',
    actionType: 'lembrete_cobranca',
  },
  {
    id: 'act-2',
    priority: 'urgente',
    category: 'financeiro',
    title: 'Cobrança vencida há 2 dias (R$ 2.450)',
    description: 'Exclusive Motors possui boleto Asaas emitido e em atraso.',
    value: 2450,
    dueDate: '03/09/2026',
    clientId: 'cli-exclusive',
    clientName: 'Exclusive Motors',
    responsible: 'Marlon Ribeiro',
    actionType: 'lembrete_cobranca',
  },
  {
    id: 'act-3',
    priority: 'alta',
    category: 'contratos',
    title: 'Contrato aguardando revisão interna',
    description: 'Renovação enviada para Eduardo Costa (Costa Consultoria) há 48h sem assinatura.',
    value: 4500,
    dueDate: '07/09/2026',
    clientId: 'cli-costa',
    clientName: 'Costa Consultoria',
    responsible: 'Helena Duarte',
    actionType: 'assinar_contrato',
  },
  {
    id: 'act-4',
    priority: 'alta',
    category: 'contratos',
    title: 'Contrato com término em 25 dias (Vencimento 30/09)',
    description: 'Exclusive Motors entra na janela de renovação do contrato CON-2025-0019.',
    value: 5900,
    dueDate: '30/09/2026',
    clientId: 'cli-exclusive',
    clientName: 'Exclusive Motors',
    responsible: 'Marlon Ribeiro',
    actionType: 'renovacao',
  },
  {
    id: 'act-5',
    priority: 'media',
    category: 'comercial',
    title: 'Proposta enviada sem retorno há 4 dias',
    description: 'Proposta comercial de R$ 9.800/mês para o Grupo Lumina Aguardando feedback da diretoria.',
    value: 9800,
    dueDate: '09/09/2026',
    clientName: 'Grupo Lumina',
    responsible: 'Marlon Ribeiro',
    actionType: 'retorno_proposta',
  },
  {
    id: 'act-6',
    priority: 'media',
    category: 'integracoes',
    title: 'Verificação de Webhook Asaas',
    description: '3 notificações de pagamento confirmadas com emissão automática de NFS-e realizada com sucesso.',
    dueDate: 'Hoje',
    responsible: 'Sistema',
    actionType: 'sincronizacao',
  },
];

export const initialDeals: PipelineDeal[] = [
  {
    id: 'deal-1',
    title: 'Assessoria de Tráfego e Mídia Paga',
    clientName: 'Grupo Lumina Construtora',
    contactName: 'Mariana Prado',
    amount: 9800,
    service: 'Gestão de Tráfego',
    responsible: 'Marlon Ribeiro',
    stage: 'proposta',
    nextActivity: 'Follow-up por WhatsApp',
    daysInStage: 4,
    probability: 70,
    origin: 'Indicação',
  },
  {
    id: 'deal-2',
    title: 'Reestruturação Completa de Marca e Site',
    clientName: 'BioNutri Alimentos Saudáveis',
    contactName: 'André Bastos',
    amount: 14500,
    service: 'Branding & Identidade',
    responsible: 'Marlon Ribeiro',
    stage: 'negociacao',
    nextActivity: 'Apresentar ajuste no investimento',
    daysInStage: 2,
    probability: 85,
    origin: 'Inbound Google',
  },
  {
    id: 'deal-3',
    title: 'Consultoria de Growth e Retenção',
    clientName: 'NexPay Soluções Financeiras',
    contactName: 'Juliana Rossi',
    amount: 12000,
    service: 'Consultoria de Crescimento',
    responsible: 'Helena Duarte',
    stage: 'diagnostico',
    nextActivity: 'Reunião de Diagnóstico na terça',
    daysInStage: 3,
    probability: 50,
    origin: 'Outbound LinkedIn',
  },
  {
    id: 'deal-4',
    title: 'Gestão de Conteúdo e Vídeos Curtos',
    clientName: 'OdontoPrime Estética',
    contactName: 'Dr. Fernando Dias',
    amount: 4200,
    service: 'Mídias Sociais',
    responsible: 'Helena Duarte',
    stage: 'qualificacao',
    nextActivity: 'Enviar questionário de briefing',
    daysInStage: 1,
    probability: 30,
    origin: 'Instagram',
  },
  {
    id: 'deal-5',
    title: 'Campanha de Lançamento de Software',
    clientName: 'FlowLog Logística Inteligente',
    contactName: 'Marcelo Pires',
    amount: 8900,
    service: 'Performance & Leads',
    responsible: 'Marlon Ribeiro',
    stage: 'novo_lead',
    nextActivity: 'Primeiro contato de qualificação',
    daysInStage: 1,
    probability: 20,
    origin: 'Site Form',
  },
  {
    id: 'deal-6',
    title: 'Consultoria de Inbound e Conteúdo',
    clientName: 'Alpha Tecnologia',
    contactName: 'Rodrigo Siqueira',
    amount: 8500,
    service: 'Consultoria de Crescimento',
    responsible: 'Marlon Ribeiro',
    stage: 'ganho',
    nextActivity: 'Onboarding iniciado',
    daysInStage: 30,
    probability: 100,
    origin: 'Base Existente',
  },
];

export const initialIntegrations: Integration[] = [
  {
    id: 'int-asaas',
    name: 'Asaas Pagamentos',
    category: 'pagamentos',
    description: 'Emissão de boletos, Pix dinâmico, assinaturas recorrentes com split e baixa automática via Webhook.',
    status: 'conectado',
    lastSync: 'Há 2 minutos',
    logo: 'asaas',
    connectedAccount: 'Aurora Studio (Dados demonstrativos)',
    features: ['Pix Dinâmico & Automático', 'Boletos com QR Code', 'Cartão Recorrente', 'Emissão automática de NFS-e', 'Webhooks 2.0'],
    syncEventsToday: 142,
  },
  {
    id: 'int-openfinance',
    name: 'Pluggy (Open Finance)',
    category: 'bancos',
    description: 'Importação automática de extratos de bancos tradicionais (Itaú, Bradesco, Santander) e fintechs.',
    status: 'conectado',
    lastSync: 'Hoje às 06:00',
    logo: 'pluggy',
    connectedAccount: 'Itaú Unibanco PJ (Agência 0451)',
    features: ['Saldos Consolidados', 'Extrato em Tempo Real', 'Sugestão de Conciliação'],
    syncEventsToday: 34,
  },
  {
    id: 'int-fiscal',
    name: 'Focus NFe / NFS-e',
    category: 'fiscal',
    description: 'Emissão fiscal municipal automatizada integrada com mais de 1.500 prefeituras no Brasil.',
    status: 'conectado',
    lastSync: 'Há 1 hora',
    logo: 'focus',
    connectedAccount: 'Prefeitura Municipal de São Paulo',
    features: ['Emissão após baixa de pagamento', 'Download automático de XML/PDF', 'Cancelamento integrado'],
    syncEventsToday: 9,
  },
  {
    id: 'int-whatsapp',
    name: 'WhatsApp Business API',
    category: 'comunicacao',
    description: 'Envio de cobranças, links Pix, lembretes de vencimento e contratos diretamente no WhatsApp do cliente.',
    status: 'conectado',
    lastSync: 'Em tempo real',
    logo: 'whatsapp',
    connectedAccount: '+55 11 98452-9000 (Verificado Meta)',
    features: ['Lembretes 3 dias antes', 'Aviso no dia do vencimento', 'Envio de link de assinatura'],
    syncEventsToday: 47,
  },
  {
    id: 'int-clickup',
    name: 'ClickUp / Asana',
    category: 'produtividade',
    description: 'Criação automática de espaço de trabalho e checklist de onboarding assim que o contrato for assinado.',
    status: 'em_breve',
    logo: 'clickup',
    features: ['Disparo de Onboarding', 'Sincronização de Tarefas', 'Horas faturáveis'],
  },
  {
    id: 'int-drive',
    name: 'Google Drive',
    category: 'arquivos',
    description: 'Backup automático de contratos assinados, comprovantes de pagamento e pastas mensais de fechamento.',
    status: 'conectado',
    lastSync: 'Ontem às 23:00',
    logo: 'drive',
    connectedAccount: 'contabilidade@aurorastudio.exemplo',
    features: ['Pastas por Cliente', 'Backup de NFS-e em PDF/XML', 'Fechamento Contábil Mensal'],
    syncEventsToday: 12,
  },
  {
    id: 'int-contaazul',
    name: 'Conta Azul ERP',
    category: 'contabilidade',
    description: 'Conciliação contábil automática e espelhamento de receitas e despesas com plano de contas.',
    status: 'conectado',
    lastSync: 'Hoje às 07:30',
    logo: 'contaazul',
    connectedAccount: 'Aurora Studio Ltda. (CNPJ 12.345.678/0001-90)',
    features: ['Plano de Contas DRE', 'Conciliação com Asaas', 'Exportação para Contabilidade Externa'],
    syncEventsToday: 26,
  },
  {
    id: 'int-mercadopago',
    name: 'Mercado Pago',
    category: 'pagamentos',
    description: 'Gateway secundário de pagamentos via cartão de crédito e link de pagamento para clientes internacionais.',
    status: 'conectado',
    lastSync: 'Há 45 minutos',
    logo: 'mercadopago',
    connectedAccount: 'financeiro@aurorastudio.exemplo',
    features: ['Checkout Transparente', 'Parcelamento em até 12x', 'Anticipação de Recebíveis'],
    syncEventsToday: 8,
  },
  {
    id: 'int-rdstation',
    name: 'RD Station CRM',
    category: 'comercial',
    description: 'Criação de novos clientes no sistema assim que o lead é marcado como ganho no funil de vendas.',
    status: 'conectado',
    lastSync: 'Há 10 minutos',
    logo: 'rdstation',
    connectedAccount: 'equipe@aurorastudio.exemplo (Workspace Aurora)',
    features: ['Disparo de Onboarding', 'Sincronização de Contatos', 'Histórico de Conversão'],
    syncEventsToday: 15,
  },
  {
    id: 'int-slack',
    name: 'Slack Notificações',
    category: 'comunicacao',
    description: 'Alertas em tempo real nos canais #financeiro-alertas e #novos-contratos para toda a equipe.',
    status: 'conectado',
    lastSync: 'Em tempo real',
    logo: 'slack',
    connectedAccount: 'aurora-estudos.slack.com',
    features: ['Avisos de Pix Recebido', 'Alertas de Inadimplência > 5 dias', 'Contrato aprovado internamente'],
    syncEventsToday: 53,
  },
];

export const clientTimelineSample: TimelineEvent[] = [
  {
    id: 't-1',
    date: 'Hoje às 10:15',
    title: 'Cobrança Pix Vencida',
    description: 'Mensalidade de R$ 2.450 venceu há 3 dias sem identificação de crédito no Asaas.',
    type: 'cobranca',
    statusBadge: 'Vencida',
    amount: 2450,
  },
  {
    id: 't-2',
    date: '02/09/2026 às 08:00',
    title: 'Lembrete enviado via WhatsApp',
    description: 'Template oficial de lembrete amigável com código Pix Copia e Cola enviado para Camila Guimarães.',
    type: 'contato',
    responsible: 'Sistema (Automação)',
  },
  {
    id: 't-3',
    date: '28/08/2026 às 14:20',
    title: 'Reunião de Alinhamento Mensal',
    description: 'Apresentação dos resultados de tráfego. Cliente solicitou ampliação da verba de Meta Ads em 20%.',
    type: 'tarefa',
    responsible: 'Marlon Ribeiro',
  },
  {
    id: 't-4',
    date: '10/08/2026 às 11:30',
    title: 'Pagamento Confirmado no Asaas',
    description: 'Mensalidade de julho liquidada com sucesso via Pix QR Code.',
    type: 'cobranca',
    statusBadge: 'Recebida',
    amount: 7200,
  },
  {
    id: 't-5',
    date: '10/08/2026 às 11:32',
    title: 'Nota Fiscal Emitida Automaticamente',
    description: 'NFS-e Nº 2026/0488 emitida na Prefeitura de São Paulo e enviada para o e-mail financeiro.',
    type: 'nota_fiscal',
    statusBadge: 'Emitida',
  },
  {
    id: 't-6',
    date: '05/01/2026 às 17:00',
    title: 'Contrato aprovado internamente',
    description: 'Contrato CON-2026-0042 assinado com certificado digital por Camila Guimarães e Marlon Ribeiro.',
    type: 'contrato',
    statusBadge: 'Assinado',
  },
];

export const cashflowData = [
  { month: 'Mar', entradas: 175000, saidas: 110000, acumulado: 120000 },
  { month: 'Abr', entradas: 190000, saidas: 125000, acumulado: 185000 },
  { month: 'Mai', entradas: 182000, saidas: 130000, acumulado: 237000 },
  { month: 'Jun', entradas: 205000, saidas: 128000, acumulado: 314000 },
  { month: 'Jul', entradas: 215000, saidas: 135000, acumulado: 394000 },
  { month: 'Ago', entradas: 198000, saidas: 112000, acumulado: 480000 },
  { month: 'Set', entradas: 224000, saidas: 138000, acumulado: 566000 },
];

export const initialAsaasCharges: AsaasChargeItem[] = [
  {
    id: 'asaas-chg-1',
    clientName: 'Alpha Ltda',
    clientId: 'cli-alpha',
    amount: 5200,
    method: 'Pix',
    status: 'pago',
    statusDotColor: 'blue',
    dueDate: '10/09/2026',
    invoiceGenerated: true,
    invoiceNumber: 'NFS-e 2026/0512',
    asaasId: 'pay_9283019283',
    description: 'Mensalidade de Gestão de Mídia de Performance e Analytics',
    createdAt: '01/09/2026',
    pixCopiaECola: '00020126580014br.gov.bcb.pix0136asaas-cobranca-pix-alpha-520052040000530398654055200.005802BR5913Dubbo Marketing6009Sao Paulo62070503***6304E8A1',
  },
  {
    id: 'asaas-chg-2',
    clientName: 'Beta ME',
    amount: 3800,
    method: 'Boleto',
    status: 'pendente',
    statusDotColor: 'yellow',
    dueDate: '15/09/2026',
    invoiceGenerated: false,
    asaasId: 'pay_7192840192',
    description: 'Serviços de Conteúdo e Posicionamento Digital',
    createdAt: '02/09/2026',
    bankSlipCode: '03399.01234 56789.012345 67890.123456 1 98450000380000',
  },
  {
    id: 'asaas-chg-3',
    clientName: 'Gamma SA',
    amount: 12000,
    method: 'Pix',
    status: 'pago',
    statusDotColor: 'blue',
    dueDate: '08/09/2026',
    invoiceGenerated: true,
    invoiceNumber: 'NFS-e 2026/0510',
    asaasId: 'pay_3849201948',
    description: 'Consultoria Estratégica Trimestral e Otimização CRO',
    createdAt: '28/08/2026',
    pixCopiaECola: '00020126580014br.gov.bcb.pix0136asaas-cobranca-pix-gamma-12000520400005303986540712000.005802BR5913Dubbo Marketing6009Sao Paulo62070503***6304F2B7',
  },
  {
    id: 'asaas-chg-4',
    clientName: 'Delta EIRELI',
    amount: 2450,
    method: 'Boleto',
    status: 'pago',
    statusDotColor: 'blue',
    dueDate: '05/09/2026',
    invoiceGenerated: true,
    invoiceNumber: 'NFS-e 2026/0508',
    asaasId: 'pay_1092837461',
    description: 'Manutenção de Infraestrutura Digital e SEO Local',
    createdAt: '25/08/2026',
    bankSlipCode: '03399.98765 43210.987654 32109.876543 2 98420000245000',
  },
  {
    id: 'asaas-chg-5',
    clientName: 'Epsilon ME',
    amount: 4100,
    method: 'Pix',
    status: 'pago',
    statusDotColor: 'blue',
    dueDate: '07/09/2026',
    invoiceGenerated: true,
    invoiceNumber: 'NFS-e 2026/0509',
    asaasId: 'pay_4829104829',
    description: 'Gestão de Tráfego Pago e Copywriting Estratégico',
    createdAt: '27/08/2026',
    pixCopiaECola: '00020126580014br.gov.bcb.pix0136asaas-cobranca-pix-epsilon-410052040000530398654054100.005802BR5913Dubbo Marketing6009Sao Paulo62070503***6304A3C9',
  },
  {
    id: 'asaas-chg-6',
    clientName: 'Studio Horizonte Arquitetura',
    clientId: 'cli-horizonte',
    amount: 11400,
    method: 'Pix',
    status: 'pago',
    statusDotColor: 'green',
    dueDate: '10/09/2026',
    invoiceGenerated: true,
    invoiceNumber: 'NFS-e 2026/0513',
    asaasId: 'pay_6672819203',
    description: 'Assessoria de Comunicação e Branding',
    createdAt: '01/09/2026',
    pixCopiaECola: '00020126580014br.gov.bcb.pix0136asaas-cobranca-pix-horizonte-11400520400005303986540711400.005802BR5913Dubbo Marketing6009Sao Paulo62070503***6304B1E4',
  },
  {
    id: 'asaas-chg-7',
    clientName: 'Clínica Integrada Vitta',
    clientId: 'cli-vitta',
    amount: 3800,
    method: 'Pix',
    status: 'pago',
    statusDotColor: 'green',
    dueDate: '05/09/2026',
    invoiceGenerated: true,
    invoiceNumber: 'NFS-e 2026/0507',
    asaasId: 'pay_8849102938',
    description: 'Mensalidade Posicionamento Digital',
    createdAt: '28/08/2026',
    pixCopiaECola: '00020126580014br.gov.bcb.pix0136asaas-cobranca-pix-vitta-380052040000530398654053800.005802BR5913Dubbo Marketing6009Sao Paulo62070503***6304C2D1',
  },
  {
    id: 'asaas-chg-8',
    clientName: 'Costa Consultoria',
    amount: 4500,
    method: 'Boleto',
    status: 'pendente',
    statusDotColor: 'yellow',
    dueDate: '12/09/2026',
    invoiceGenerated: false,
    asaasId: 'pay_5548192031',
    description: 'Primeira Parcela do Novo Contrato Estratégico',
    createdAt: '02/09/2026',
    bankSlipCode: '03399.11223 34455.667788 99001.122334 3 98430000450000',
  },
];

export const initialServiceInvoices: ServiceInvoice[] = [
  {
    id: 'nfse-2026-0513',
    number: '2026/0513',
    rpsNumber: 'RPS 1409',
    clientId: 'cli-horizonte',
    clientName: 'Studio Horizonte Arquitetura Ltda',
    clientDocument: '28.192.403/0001-92',
    amount: 11400,
    issueDate: '05/09/2026 às 14:10',
    competence: '09/2026',
    serviceDescription: 'Assessoria de Comunicação e Branding Estratégico Corporativo',
    municipalServiceCode: '17.06 - Propaganda e publicidade, inclusive promoção de vendas',
    status: 'autorizada',
    city: 'São Paulo - SP',
    issRate: 2.0,
    retentions: {
      iss: 228,
      pis: 74.1,
      cofins: 342,
      csll: 114,
      ir: 171,
    },
    asaasInvoiceId: 'inv_8492019482',
    sentByEmail: true,
    pdfUrl: '#',
    xmlUrl: '#',
  },
  {
    id: 'nfse-2026-0512',
    number: '2026/0512',
    rpsNumber: 'RPS 1408',
    clientId: 'cli-alpha',
    clientName: 'Alpha Ltda',
    clientDocument: '42.610.778/0001-31',
    amount: 5200,
    issueDate: '04/09/2026 às 16:22',
    competence: '09/2026',
    serviceDescription: 'Gestão de Mídia de Performance, Campanhas de Tráfego e Otimização de Conversão',
    municipalServiceCode: '17.06 - Propaganda e publicidade',
    status: 'autorizada',
    city: 'São Paulo - SP',
    issRate: 2.0,
    retentions: {
      iss: 104,
      pis: 33.8,
      cofins: 156,
      csll: 52,
      ir: 78,
    },
    asaasInvoiceId: 'inv_7192849102',
    sentByEmail: true,
    pdfUrl: '#',
    xmlUrl: '#',
  },
  {
    id: 'nfse-2026-0510',
    number: '2026/0510',
    rpsNumber: 'RPS 1407',
    clientId: 'cli-gamma',
    clientName: 'Gamma SA',
    clientDocument: '18.491.029/0001-55',
    amount: 12000,
    issueDate: '03/09/2026 às 10:45',
    competence: '09/2026',
    serviceDescription: 'Consultoria Estratégica Trimestral e Otimização de Funil Digital',
    municipalServiceCode: '17.01 - Assessoria ou consultoria de qualquer natureza',
    status: 'autorizada',
    city: 'São Paulo - SP',
    issRate: 2.0,
    retentions: {
      iss: 240,
      pis: 78,
      cofins: 360,
      csll: 120,
      ir: 180,
    },
    asaasInvoiceId: 'inv_3948201948',
    sentByEmail: true,
    pdfUrl: '#',
    xmlUrl: '#',
  },
  {
    id: 'nfse-2026-0509',
    number: '2026/0509',
    rpsNumber: 'RPS 1406',
    clientId: 'cli-epsilon',
    clientName: 'Epsilon ME',
    clientDocument: '50.192.834/0001-90',
    amount: 4100,
    issueDate: '02/09/2026 às 11:30',
    competence: '09/2026',
    serviceDescription: 'Gestão de Campanhas de Tráfego Pago e Copywriting',
    municipalServiceCode: '17.06 - Propaganda e publicidade',
    status: 'autorizada',
    city: 'São Paulo - SP',
    issRate: 2.0,
    retentions: {
      iss: 82,
      pis: 26.65,
      cofins: 123,
      csll: 41,
      ir: 61.5,
    },
    asaasInvoiceId: 'inv_5829104829',
    sentByEmail: true,
    pdfUrl: '#',
    xmlUrl: '#',
  },
  {
    id: 'nfse-2026-0508',
    number: '2026/0508',
    rpsNumber: 'RPS 1405',
    clientId: 'cli-delta',
    clientName: 'Delta EIRELI',
    clientDocument: '31.849.201/0001-83',
    amount: 2450,
    issueDate: '01/09/2026 às 09:15',
    competence: '09/2026',
    serviceDescription: 'Manutenção de Infraestrutura Digital, Hospedagem e SEO',
    municipalServiceCode: '1.03 - Processamento de dados e congêneres',
    status: 'autorizada',
    city: 'São Paulo - SP',
    issRate: 2.0,
    retentions: {
      iss: 49,
      pis: 15.9,
      cofins: 73.5,
      csll: 24.5,
      ir: 36.75,
    },
    asaasInvoiceId: 'inv_1092837461',
    sentByEmail: true,
    pdfUrl: '#',
    xmlUrl: '#',
  },
  {
    id: 'nfse-2026-0507',
    number: '2026/0507',
    rpsNumber: 'RPS 1404',
    clientId: 'cli-vitta',
    clientName: 'Clínica Integrada Vitta Medicina',
    clientDocument: '19.782.934/0001-18',
    amount: 3800,
    issueDate: '01/09/2026 às 08:30',
    competence: '09/2026',
    serviceDescription: 'Gestão de Mídias Sociais e Posicionamento Digital de Especialistas',
    municipalServiceCode: '17.06 - Propaganda e publicidade',
    status: 'autorizada',
    city: 'Belo Horizonte - MG',
    issRate: 2.0,
    retentions: {
      iss: 76,
      pis: 24.7,
      cofins: 114,
      csll: 38,
      ir: 57,
    },
    asaasInvoiceId: 'inv_8849102938',
    sentByEmail: true,
    pdfUrl: '#',
    xmlUrl: '#',
  },
  {
    id: 'nfse-2026-0506',
    number: '2026/0506',
    rpsNumber: 'RPS 1403',
    clientId: 'cli-aurora',
    clientName: 'Aurora Marketing Digital',
    clientDocument: '34.892.120/0001-44',
    amount: 8850,
    issueDate: '31/08/2026 às 17:00',
    competence: '08/2026',
    serviceDescription: 'Consultoria de Inbound e Tráfego Pago Competência Agosto',
    municipalServiceCode: '17.06 - Propaganda e publicidade',
    status: 'autorizada',
    city: 'São Paulo - SP',
    issRate: 2.0,
    retentions: {
      iss: 177,
      pis: 57.5,
      cofins: 265.5,
      csll: 88.5,
      ir: 132.75,
    },
    asaasInvoiceId: 'inv_9938201923',
    sentByEmail: true,
    pdfUrl: '#',
    xmlUrl: '#',
  },
];

export const initialBankAccounts: BankAccount[] = [
  {
    id: 'acc-itau',
    bankName: 'Itaú - CC',
    bankCode: '341',
    agency: '0451',
    accountNumber: '19.824-3',
    currentBalance: -8433.59,
    reconciledBalance: 51820.62,
    pendingReconciliationAmount: 60254.21,
    pendingReconciliationCount: 5,
    lastSyncDate: '05/09/2026 às 07h37',
    lastImportedDate: '04/09/2026',
    provider: 'open_finance',
  },
  {
    id: 'acc-asaas',
    bankName: 'Asaas Conta Digital',
    bankCode: 'asaas',
    agency: '0001',
    accountNumber: '482918-0',
    currentBalance: 42380.00,
    reconciledBalance: 42380.00,
    pendingReconciliationAmount: 0.00,
    pendingReconciliationCount: 0,
    lastSyncDate: 'Hoje às 08h15',
    lastImportedDate: 'Hoje',
    provider: 'asaas',
  },
  {
    id: 'acc-santander',
    bankName: 'Santander PJ',
    bankCode: '033',
    agency: '2105',
    accountNumber: '13.002.941-8',
    currentBalance: 14750.30,
    reconciledBalance: 14750.30,
    pendingReconciliationAmount: 0.00,
    pendingReconciliationCount: 0,
    lastSyncDate: '04/09/2026 às 18h00',
    lastImportedDate: '04/09/2026',
    provider: 'pluggy',
  },
];

export const initialBankTransactions: BankTransaction[] = [
  {
    id: 'tx-1',
    accountId: 'acc-itau',
    date: '01/09/2026',
    dayOfWeek: 'Terça-Feira',
    rawDescription: 'SISPAG FORNECEDORES',
    amount: -26801.42,
    type: 'pagamento',
    channel: 'sispag',
    counterpartyRaw: 'Informação não recebida',
    cpfCnpjRaw: 'Informação não recebida',
    status: 'pendente',
    aiAnalysis: {
      confidence: 0.98,
      interpretedEntity: 'SisPag Fornecedores & Prestadores (Lote Quinzenal)',
      interpretedCategory: 'Outras Despesas',
      interpretedCostCenter: 'Operações',
      explanation: 'A IA identificou o débito automático em lote SISPAG e cruzou com o lote quinzenal de 7 prestadores de design e tráfego da agência cadastrados em Contas a Pagar.',
      suggestedDocumentType: 'payable',
      suggestedDocumentCode: 'CP-LOTE-2026-09A',
      autoMatchRule: 'Lote SISPAG + Valor Quinzenal Contas a Pagar',
    },
    matchedDescription: 'SISPAG FORNECEDORES',
    matchedCategory: 'Outras Despesas',
    matchedSupplierOrClient: 'Lote Fornecedores Operacionais',
    matchedCostCenter: 'Operações',
    matchedType: 'novo_lancamento',
  },
  {
    id: 'tx-2',
    accountId: 'acc-itau',
    date: '02/09/2026',
    dayOfWeek: 'Quarta-Feira',
    rawDescription: 'PAG BOLETO META PLATFORMS BRASIL',
    amount: -15450.00,
    type: 'pagamento',
    channel: 'boleto',
    counterpartyRaw: 'META PLATFORMS SERVICOS DO BRASIL LTDA',
    cpfCnpjRaw: '13.347.016/0001-17',
    status: 'pendente',
    aiAnalysis: {
      confidence: 0.99,
      interpretedEntity: 'Meta Platforms (Facebook & Instagram Ads)',
      interpretedCategory: 'Mídia Paga (Tráfego)',
      interpretedCostCenter: 'Mídia / Performance',
      explanation: 'A IA leu o código de barras e o CNPJ 13.347.016/0001-17 da Meta Platforms. Vinculou automaticamente com a Conta a Pagar #CP-2026-079 (Mídia do Cliente Alpha Ltda).',
      suggestedDocumentType: 'payable',
      suggestedDocumentCode: 'CP-2026-079',
      autoMatchRule: 'Reconhecimento de CNPJ + Boleto Bancário Registrado',
    },
    matchedDescription: 'PAG BOLETO META PLATFORMS BRASIL',
    matchedCategory: 'Mídia Paga (Tráfego)',
    matchedSupplierOrClient: 'Meta Platforms Brasil',
    matchedCostCenter: 'Mídia / Performance',
    matchedType: 'buscar_lancamento',
  },
  {
    id: 'tx-3',
    accountId: 'acc-itau',
    date: '03/09/2026',
    dayOfWeek: 'Quinta-Feira',
    rawDescription: 'PGTO TRIB FED DARF SIMPLES NACIONAL',
    amount: -9842.19,
    type: 'pagamento',
    channel: 'debito_automatico',
    counterpartyRaw: 'RECEITA FEDERAL DO BRASIL',
    cpfCnpjRaw: '00.394.460/0058-87',
    status: 'pendente',
    aiAnalysis: {
      confidence: 0.97,
      interpretedEntity: 'Receita Federal - Simples Nacional (DAS)',
      interpretedCategory: 'Impostos & Tributos',
      interpretedCostCenter: 'Administrativo',
      explanation: 'A IA detectou código de arrecadação do Simples Nacional (DAS), apurado sobre a competência 08/2026 das notas fiscais emitidas no Asaas.',
      suggestedDocumentType: 'payable',
      suggestedDocumentCode: 'CP-2026-081',
      autoMatchRule: 'Padrão DARF Receita Federal + Fechamento Fiscal',
    },
    matchedDescription: 'PGTO TRIB FED DARF SIMPLES NACIONAL',
    matchedCategory: 'Impostos & Tributos',
    matchedSupplierOrClient: 'Receita Federal (DAS Simples)',
    matchedCostCenter: 'Administrativo',
    matchedType: 'novo_lancamento',
  },
  {
    id: 'tx-4',
    accountId: 'acc-itau',
    date: '03/09/2026',
    dayOfWeek: 'Quinta-Feira',
    rawDescription: 'DEB AUT ENEL DISTRIB SP',
    amount: -1450.60,
    type: 'pagamento',
    channel: 'debito_automatico',
    counterpartyRaw: 'ENEL DISTRIBUICAO SAO PAULO',
    cpfCnpjRaw: '61.695.227/0001-93',
    status: 'pendente',
    aiAnalysis: {
      confidence: 0.96,
      interpretedEntity: 'Enel Distribuição São Paulo',
      interpretedCategory: 'Infraestrutura / Contas de Consumo',
      interpretedCostCenter: 'Administrativo',
      explanation: 'A IA identificou débito automático de energia elétrica da sede da agência em Moema, correspondente à despesa fixa mensal #CP-2026-083.',
      suggestedDocumentType: 'payable',
      suggestedDocumentCode: 'CP-2026-083',
      autoMatchRule: 'Débito Recorrente Mensal + Concessionária de Energia',
    },
    matchedDescription: 'DEB AUT ENEL DISTRIB SP',
    matchedCategory: 'Infraestrutura / Contas de Consumo',
    matchedSupplierOrClient: 'Enel Distribuição SP',
    matchedCostCenter: 'Administrativo',
    matchedType: 'buscar_lancamento',
  },
  {
    id: 'tx-5',
    accountId: 'acc-itau',
    date: '04/09/2026',
    dayOfWeek: 'Sexta-Feira',
    rawDescription: 'PIX TRANSF DEMO ADIANTAMENTO DIRETORIA',
    amount: -6710.00,
    type: 'pagamento',
    channel: 'pix',
    counterpartyRaw: 'RAFAEL NOGUEIRA (SOCIO)',
    cpfCnpjRaw: '123.456.789-09',
    status: 'pendente',
    aiAnalysis: {
      confidence: 0.95,
      interpretedEntity: 'Marlon Ribeiro (Pró-Labore & Sócios)',
      interpretedCategory: 'Pró-Labore & Sócios',
      interpretedCostCenter: 'Diretoria',
      explanation: 'A IA reconheceu a chave Pix e CPF do sócio-administrador Marlon Ribeiro e vinculou ao adiantamento quinzenal de pró-labore do mês de setembro.',
      suggestedDocumentType: 'payable',
      suggestedDocumentCode: 'CP-2026-085',
      autoMatchRule: 'Chave Pix Sócio Cadastrado + Pró-Labore Programado',
    },
    matchedDescription: 'PIX TRANSF DEMO ADIANTAMENTO DIRETORIA',
    matchedCategory: 'Pró-Labore & Sócios',
    matchedSupplierOrClient: 'Rafael Nogueira',
    matchedCostCenter: 'Diretoria',
    matchedType: 'novo_lancamento',
  },
  {
    id: 'tx-6',
    accountId: 'acc-itau',
    date: '01/09/2026',
    dayOfWeek: 'Terça-Feira',
    rawDescription: 'PIX RECEBIDO - AURORA MARKETING DIGITAL',
    amount: 8850.00,
    type: 'recebimento',
    channel: 'pix',
    counterpartyRaw: 'AURORA MARKETING DIGITAL LTDA',
    cpfCnpjRaw: '34.892.120/0001-44',
    status: 'conciliado',
    aiAnalysis: {
      confidence: 1.0,
      interpretedEntity: 'Aurora Marketing Digital',
      interpretedCategory: 'Receita de Serviços (Recorrente)',
      interpretedCostCenter: 'Operações',
      explanation: 'Conciliado automaticamente pela IA com a Fatura Asaas #9938 e Contrato CTR-2026-03.',
      suggestedDocumentType: 'receivable',
      suggestedDocumentCode: 'CR-2026-041',
      autoMatchRule: 'Identificação Exata por CNPJ e Valor de Mensalidade',
    },
    matchedDescription: 'PIX RECEBIDO - AURORA MARKETING DIGITAL',
    matchedCategory: 'Receita de Serviços (Recorrente)',
    matchedSupplierOrClient: 'Aurora Marketing Digital',
    matchedCostCenter: 'Operações',
    matchedType: 'buscar_lancamento',
    reconciledAt: '01/09/2026 às 10:14',
    reconciledBy: 'IA Conciliadora Automática',
  },
  {
    id: 'tx-7',
    accountId: 'acc-itau',
    date: '31/08/2026',
    dayOfWeek: 'Segunda-Feira',
    rawDescription: 'TED RECEBIDA - ALPHA COMERCIO E CONSULTORIA',
    amount: 15000.00,
    type: 'recebimento',
    channel: 'ted',
    counterpartyRaw: 'ALPHA CONSULTORIA LTDA',
    cpfCnpjRaw: '12.345.678/0001-90',
    status: 'conciliado',
    aiAnalysis: {
      confidence: 0.99,
      interpretedEntity: 'Alpha Ltda',
      interpretedCategory: 'Receita de Serviços (Contrato)',
      interpretedCostCenter: 'Operações',
      explanation: 'Conciliado automaticamente pela IA com o Contrato Ativo CTR-2026-01 (Mensalidade de Performance).',
      suggestedDocumentType: 'receivable',
      suggestedDocumentCode: 'CR-2026-039',
      autoMatchRule: 'Cruzamento de Valor R$ 15.000 + CNPJ Alpha Ltda',
    },
    matchedDescription: 'TED RECEBIDA - ALPHA COMERCIO E CONSULTORIA',
    matchedCategory: 'Receita de Serviços (Contrato)',
    matchedSupplierOrClient: 'Alpha Ltda',
    matchedCostCenter: 'Operações',
    matchedType: 'buscar_lancamento',
    reconciledAt: '31/08/2026 às 16:30',
    reconciledBy: 'IA Conciliadora Automática',
  },
  {
    id: 'tx-8',
    accountId: 'acc-itau',
    date: '28/08/2026',
    dayOfWeek: 'Sexta-Feira',
    rawDescription: 'PAG ELETRONICO - GOOGLE BRASIL INTERNET LTDA',
    amount: -12400.00,
    type: 'pagamento',
    channel: 'ted',
    counterpartyRaw: 'GOOGLE BRASIL INTERNET LTDA',
    cpfCnpjRaw: '06.990.590/0001-04',
    status: 'conciliado',
    aiAnalysis: {
      confidence: 1.0,
      interpretedEntity: 'Google Brasil (Google Ads)',
      interpretedCategory: 'Mídia Paga (Tráfego)',
      interpretedCostCenter: 'Mídia / Performance',
      explanation: 'Conciliado com Nota Fiscal de Prestação de Mídia do Google Ads para clientes de tráfego pago.',
      suggestedDocumentType: 'payable',
      suggestedDocumentCode: 'CP-2026-075',
      autoMatchRule: 'CNPJ Google Brasil + Linha Digitável de Boleto',
    },
    matchedDescription: 'PAG ELETRONICO - GOOGLE BRASIL INTERNET LTDA',
    matchedCategory: 'Mídia Paga (Tráfego)',
    matchedSupplierOrClient: 'Google Brasil Internet Ltda',
    matchedCostCenter: 'Mídia / Performance',
    matchedType: 'buscar_lancamento',
    reconciledAt: '28/08/2026 às 11:20',
    reconciledBy: 'IA Conciliadora Automática',
  },
];
